name: Update README

on:
  workflow_dispatch:
  push:
    paths: [completed]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - run: |
          echo '<p align="center">' >> README.md
          echo '<img src="media/MyAnimeListLogo.png" >' >> README.md
          echo '#' >> README.md         
          echo "" >> README.md
          total=$(grep -oP 'anime/\K[0-9]+' completed | wc -l)
          current=0
          
          grep -oP 'anime/\K[0-9]+' completed | while read id; do
            current=$((current + 1))
            echo "[$current/$total] Fetching anime ID: $id"
            
            # Intentar obtener imagen del endpoint principal
            response=$(curl -s "https://api.jikan.moe/v4/anime/$id")
            image_url=$(echo "$response" | jq -r '.data.images.jpg.image_url // empty')
            
            # Fallback: buscar en /pictures si no hay imagen
            if [ -z "$image_url" ]; then
              echo "  ⚠ No image in main endpoint, trying /pictures..."
              pics_response=$(curl -s "https://api.jikan.moe/v4/anime/$id/pictures")
              image_url=$(echo "$pics_response" | jq -r '.data[0].jpg.image_url // .data[0].jpg.large_image_url // empty')
              sleep 0.5  # Rate limit adicional para segunda llamada
            fi
            
            if [ -n "$image_url" ]; then
              echo "  ✓ Image found: $image_url"
              echo -n "<a href=\"https://myanimelist.net/anime/$id\"><img src=\"$image_url\" width=\"225\" height=\"300\"></a> " >> README.md
            else
              echo "  ✗ No image available for ID: $id"
            fi
            
            sleep 0.5
          done
          
          echo "</p>" >> README.md
          echo "" >> README.md
          echo "Finished processing $total anime entries"
      
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || (git commit -m "Update [skip ci]" && git push)
